import { NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * Serves the precomputed pool payout analysis (public/data/pool-payouts.json),
 * generated by `pnpm pool-payouts`. Kept as a route (rather than reading the
 * static file directly) so a "generated at" freshness value is always returned
 * and a missing file degrades to a clear message instead of a 404.
 */
export async function GET() {
    try {
        const filePath = join(process.cwd(), 'public', 'data', 'pool-payouts.json');
        const data = JSON.parse(readFileSync(filePath, 'utf8'));
        return NextResponse.json(data);
    } catch {
        return NextResponse.json(
            {
                generatedAt: null,
                pools: [],
                error: 'Pool payout data is not available yet. Please check back shortly.',
            },
            { status: 200 },
        );
    }
}
