import { NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * Serves the precomputed pool payout analysis (public/data/pool-payouts.json),
 * generated by `pnpm pool-payouts`, and annotates each pool's consolidation
 * addresses with any known entity (exchange / pool / service) they belong to —
 * cross-referenced against exchange-addresses.json at serve time so labels stay
 * current without regenerating the pool data. This surfaces pool→exchange flows
 * (e.g. a pool whose "consolidation" destination is actually a CoinEx or MEXC
 * deposit address).
 */
export async function GET() {
    try {
        const dataDir = join(process.cwd(), 'public', 'data');
        const pools = JSON.parse(readFileSync(join(dataDir, 'pool-payouts.json'), 'utf8'));

        // address -> { name, type }
        const owner = new Map<string, { name: string; type: string }>();
        try {
            const entities = JSON.parse(readFileSync(join(dataDir, 'exchange-addresses.json'), 'utf8'));
            const sections: Array<[string, string]> = [
                ['exchange', 'exchanges'],
                ['pool', 'mining_pools'],
                ['service', 'services'],
            ];
            for (const [type, key] of sections) {
                for (const e of Object.values(entities[key] || {}) as Array<{ name: string; addresses?: string[] }>) {
                    for (const a of e.addresses || []) if (!owner.has(a)) owner.set(a, { name: e.name, type });
                }
            }
        } catch {
            // entities file missing — serve pool data without entity labels
        }

        for (const p of pools.pools || []) {
            for (const c of p.consolidatesTo || []) {
                const o = owner.get(c.address);
                if (o) { c.entity = o.name; c.entityType = o.type; }
            }
        }

        return NextResponse.json(pools);
    } catch {
        return NextResponse.json(
            {
                generatedAt: null,
                pools: [],
                error: 'Pool payout data is not available yet. Please check back shortly.',
            },
            { status: 200 },
        );
    }
}
