import { NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * Serves the precomputed pool payout analysis (public/data/pool-payouts.json),
 * generated by `pnpm pool-payouts`, and annotates each pool's consolidation
 * addresses with any known entity (exchange / pool / service) they belong to —
 * cross-referenced against exchange-addresses.json at serve time so labels stay
 * current without regenerating the pool data. This surfaces pool→exchange flows
 * (e.g. a pool whose "consolidation" destination is actually a CoinEx or MEXC
 * deposit address).
 */
export async function GET() {
    try {
        const dataDir = join(process.cwd(), 'public', 'data');
        const pools = JSON.parse(readFileSync(join(dataDir, 'pool-payouts.json'), 'utf8'));

        // address -> { name, type }
        const owner = new Map<string, { name: string; type: string }>();
        try {
            const entities = JSON.parse(readFileSync(join(dataDir, 'exchange-addresses.json'), 'utf8'));
            const sections: Array<[string, string]> = [
                ['exchange', 'exchanges'],
                ['pool', 'mining_pools'],
                ['service', 'services'],
            ];
            for (const [type, key] of sections) {
                for (const e of Object.values(entities[key] || {}) as Array<{ name: string; addresses?: string[] }>) {
                    for (const a of e.addresses || []) if (!owner.has(a)) owner.set(a, { name: e.name, type });
                }
            }
        } catch {
            // entities file missing — serve pool data without entity labels
        }

        // Build a per-pool "sendsTo" list: destinations that belong to a known
        // exchange are aggregated under that exchange (summing tx counts across
        // its deposit addresses), so a pool's true flow to e.g. MEXC — spread
        // over many low-count deposit addresses — is visible rather than hidden
        // behind one high-count consolidation wallet. Unlabeled destinations
        // stay as individual addresses.
        type Row = {
            kind: 'entity' | 'address';
            entity?: string; entityType?: string; address?: string;
            txCount: number; addresses: number; lastTs: number;
        };
        for (const p of pools.pools || []) {
            const byEntity = new Map<string, Row>();
            const addrs: Row[] = [];
            for (const c of (p.consolidatesTo || []) as Array<{ address: string; txCount: number; lastTs?: number }>) {
                const o = owner.get(c.address);
                if (o) {
                    const g = byEntity.get(o.name) ?? { kind: 'entity', entity: o.name, entityType: o.type, txCount: 0, addresses: 0, lastTs: 0 };
                    g.txCount += c.txCount; g.addresses += 1; g.lastTs = Math.max(g.lastTs, c.lastTs || 0);
                    byEntity.set(o.name, g);
                } else {
                    addrs.push({ kind: 'address', address: c.address, txCount: c.txCount, addresses: 1, lastTs: c.lastTs || 0 });
                }
            }
            p.sendsTo = [...byEntity.values(), ...addrs]
                .sort((a, b) => b.txCount - a.txCount)
                .slice(0, 6);
        }

        return NextResponse.json(pools);
    } catch {
        return NextResponse.json(
            {
                generatedAt: null,
                pools: [],
                error: 'Pool payout data is not available yet. Please check back shortly.',
            },
            { status: 200 },
        );
    }
}
